# for this to work, certain things must work
#  apt_release must be valid in the *current* sources list
#  apt-get update must work without errors
#  python-apt must be installed: apt-get install python-apt
#    if you still get "import apt_pkf failed"
#    try apt-get install and apt-get remove
# Error like: W: There is no public key available for the following key IDs:
#    apt-get install debian-archive-keyring
# also check for stale apt-pinning

- name: add buster repos
  apt_repository:
    repo: "{{ item }}"
    state: "{{ 'present' if 'buster' in apt_repo_releases else 'absent' }}"
    update_cache: false
    filename: debian-buster
  with_items: "{{ apt_repo_list_buster }}"
  register: apt_repo_buster_return

- name: add bullseye repos
  apt_repository:
    repo: "{{ item }}"
    state: "{{ 'present' if 'bullseye' in apt_repo_releases else 'absent' }}"
    update_cache: false
    filename: debian-bullseye
  with_items: "{{ apt_repo_list_bullseye }}"
  register: apt_repo_bullseye_return

- name: "remove old sources file (not used anymore)"
  file:
    state: absent
    path: "{{ item }}"
  with_items:
  - /etc/apt/sources.list
  - /etc/apt/sources.list.d/cdn_debian_net_debian.list
  - /etc/apt/sources.list.d/security_debian_org.list

- name: update apt packages
  apt: 
    update_cache: yes
  when:    apt_repo_buster_return.changed
        or apt_repo_bullseye_return.changed

- name: apt configurations
  template: src=apt.conf.j2 dest="/etc/apt/apt.conf"
