# for this to work, certain things must work
#  apt_release must be valid in the *current* sources list
#  apt-get update must work without errors
#  python-apt must be installed: apt-get install python-apt
#    if you still get "import apt_pkf failed"
#    try apt-get install and apt-get remove
# Error like: W: There is no public key available for the following key IDs:
#    apt-get install debian-archive-keyring
# also check for stale apt-pinning

- name: add buster repos
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: false
    filename: debian-buster
  with_items: "{{ apt_repo_list_buster }}"
  when: "'buster' in apt_repo_releases"
  register: apt_repo_buster_return

# see cleanup_task. for removal
- name: add bullseye repos
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: false
    filename: debian-bullseye
  with_items: "{{ apt_repo_list_bullseye }}"
  when: "'bullseye' in apt_repo_releases"
  register: apt_repo_bullseye_return

- name: add bookworm repos
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: false
    filename: debian-bookworm
  with_items: "{{ apt_repo_list_bookworm }}"
  when: "'bookworm' in apt_repo_releases"
  register: apt_repo_bookworm_return

- name: update apt packages
  apt: 
    update_cache: yes
  when:    apt_repo_buster_return.changed
        or apt_repo_bullseye_return.changed
        or apt_repo_bookworm_return.changed

- name: apt configurations
  template: src=apt.conf.j2 dest="/etc/apt/apt.conf"
