# collection of task from old ways of doing things...

- name: "remove old sources file (not used anymore)"
  file:
    state: absent
    path: "{{ item }}"
  loop:
  - /etc/apt/sources.list
  - /etc/apt/sources.list.d/cdn_debian_net_debian.list
  - /etc/apt/sources.list.d/security_debian_org.list
  notify: update apt cache

- name: "remove extra old sources file"
  file:
    state: absent
    path: "/etc/apt/sources.list.d/{{ item }}"
  loop: "{{ apt_repo_extra_files_to_remove }}"
  notify: update apt cache

- name: remove buster repos
  apt_repository:
    repo: "{{ item }}"
    state: absent
    update_cache: false
    filename: debian-buster
  with_items: "{{ apt_repo_list_buster }}"
  when: "'buster' not in apt_repo_releases"
  notify: update apt cache

- name: remove bullseye repos
  apt_repository:
    repo: "{{ item }}"
    state: absent
    update_cache: false
    filename: debian-bullseye
  with_items: "{{ apt_repo_list_bullseye }}"
  when: "'bullseye' not in apt_repo_releases"
  notify: update apt cache

- name: remove bookworm repos
  apt_repository:
    repo: "{{ item }}"
    state: absent
    update_cache: false
    filename: debian-bookworm
  with_items: "{{ apt_repo_list_bookworm }}"
  when: "'bookworm' not in apt_repo_releases"
  notify: update apt cache
  