#
#
#

- name: add repositories and update
  import_tasks: apt.yml
  when: generic_manage_apt
  tags: apt

- name: add local repo
  import_tasks: add_local_apt_repo.yml
  when: generic_manage_apt and apt_local_repo_enable
  tags: apt

- name: installing unattended upgrades
  import_tasks: unattended-upgrades.yml
  when: generic_manage_unattended_upgrade
  tags: 
  - apt
  - unattended_upgrades

- name: add ldap config
  import_tasks: add_ldap.yml
  when: generic_manage_ldap
  tags: ldap

- name: add SMTP smarthost
  import_tasks: smtp.yml
  when: generic_manage_smtp
  tags: smtp

- name: add iptables firewall
  import_tasks: iptables.yml
  when: generic_manage_firewall
  tags: firewall

- import_tasks: sshd.yml
  when: generic_manage_sshd
  tags: ssh

- import_tasks: network.yml
  when: generic_manage_network
  tags: network

- import_tasks: cleanup_tasks.yml
  tags:
  - never
  - cleanup