# unattended upgrades
#
# installs the package and configures upgrading of
# normal and security updates
#


- name: installing unattended-upgrade related packages
  apt: 
    name: unattended-upgrades
    state: present
  tags: apt

- name: Configuring unattended upgrade
  template: 
    src: unattended-upgrades/50unattended-upgrades.j2 
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  tags: apt
  notify: restart unattended upgrades

- name: Configuring periodic updates
  template: 
    src: unattended-upgrades/20auto-upgrades.j2 
    dest: /etc/apt/apt.conf.d/20auto-upgrades
  tags: apt
  notify: restart unattended upgrades
  
