# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.define "mail" do |server|
    server.vm.box = "debian/stretsh"
    server.vm.hostname = "mail"
  end

  config.vm.define "jessie" do |server|
    server.vm.box = "debian/jessie64"
    server.vm.hostname = "debian-jessie"
  end

  config.vm.define "stretch" do |server|
    server.vm.box = "debian/stretch64"
    server.vm.hostname = "debian-stretch"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end
end
