# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.define "mail" do |server|
    server.vm.box = "debian/stretch64"
    server.vm.hostname = "mail"
  end

  # debian/wheezy64 is not on hashicorp atlas using libvirt.
  # ok, so not testing that using "vagrant up"

  config.vm.define "debian-jessie" do |server|
    server.vm.box = "debian/jessie64"
    server.vm.hostname = "debian-jessie"
  end

  config.vm.define "debian-stretch" do |server|
    server.vm.box = "debian/stretch64"
    server.vm.hostname = "debian-stretch"
  end

  # debian/buster64 is not available yet for libvirt
  # ok, so not testing that using "vagrant up"
  # config.vm.define "debian-buster" do |server|
  #   server.vm.box = "debian/buster64"
  #   server.vm.hostname = "debian-buster"
  # end


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end

  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false, disabled: true

end
